site_name: Siddhi Store Elasticsearch
site_description: Siddhi Store Elasticsearch Extension
repo_name: Siddhi Store Elasticsearch
repo_url: https://github.com/siddhi-io/siddhi-store-elasticsearch/
edit_uri: https://github.com/siddhi-io/siddhi-store-elasticsearch/blob/master/
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/siddhi-io/siddhi
  - type: medium
    link: https://medium.com/siddhi-io
  - type: twitter
    link: https://twitter.com/siddhi_io
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- markdown.extensions.admonition
pages:
- Information: index.md
- API Docs:
  - latest: api/latest.md
  - 3.1.0: api/3.1.0.md
  - 3.0.0: api/3.0.0.md
  - 2.0.0: api/2.0.0.md
  - 1.5.0: api/1.5.0.md
  - 1.1.4: api/1.1.4.md
  - 1.1.3: api/1.1.3.md
  - 1.1.2: api/1.1.2.md
  - 1.1.1: api/1.1.1.md
  - 1.1.0: api/1.1.0.md
  - 1.0.5: api/1.0.5.md
  - 1.0.4: api/1.0.4.md
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0: api/1.0.0.md
- License: license.md
